apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: koalatech-user-service
  namespace: monitoring
  labels:
    release: koalatech-monitoring
spec:
  namespaceSelector:
    matchNames:
      - staging
      - production
  selector:
    matchLabels:
      app: user-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
